// frontend/lit/src/features/game/component/canvas-game.ts
import { LitElement, html, css, unsafeCSS, type PropertyValues } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import grass from "../../../assets/images/grass.png";
import playerImage from "../../../assets/images/player.png";
import { Player } from "../model/player";
import type { Item } from "../model/Item";

@customElement("canvas-game")
export class CanvasGame extends LitElement {
  static styles = [
    css`
      canvas {
        background: url(${unsafeCSS(grass)}) no-repeat;
        background-size: cover;
        border: 2px solid black;
        image-rendering: pixelated;
      }
    `,
  ];

  scope: Document = document;

  @property({ type: Array })
  lootItems: Array<Item> = [];

  @property({ type: String })
  eventName: string = "";

  canvasWidth: number = 1000;
  canvasHeight: number = 600;

  @property({ type: Number })
  playerX: number = 0;

  @property({ type: Number })
  playerY: number = 0;

  protected updated(changedProperties: PropertyValues) {
    if (changedProperties.has("playerX") || changedProperties.has("playerY")) {
      this.player.updateCoordinates(this.playerX, this.playerY);
      this.updateCharacter();
    }
  }

  player: Player = new Player(0, 0, 64, 64, playerImage, this.canvasWidth, this.canvasHeight);

  ctx: CanvasRenderingContext2D;

  //after component is loaded
  protected firstUpdated(_changedProperties: PropertyValues): void {
    const canvas: HTMLCanvasElement = this.shadowRoot?.querySelector("canvas");
    canvas.width = this.canvasWidth;
    canvas.height = this.canvasHeight;
    const drawingSurface: CanvasRenderingContext2D = canvas?.getContext("2d");
    if (!drawingSurface) {
      return;
    }
    this.initGame(drawingSurface);

    // Automatically focus the section so keyboard works
    const section: HTMLElement = this.shadowRoot?.querySelector("section");
    section?.focus();
  }

  async initGame(drawingSurface: CanvasRenderingContext2D) {
    this.ctx = drawingSurface;

    //wait for image to load
    const playerImage = this.player.getImage();
    playerImage.onload = () => {
      this.updateCharacter();
    };
    console.log(this.lootItems);
    // requestAnimationFrame(this.updateCharacter);
  }

  draw() {
    //https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage
    //clear and redraw
    this.ctx.clearRect(0, 0, this.canvasWidth, this.canvasHeight);
    this.ctx.drawImage(
      this.player.getImage(),
      Math.floor(this.player.getX()),
      Math.floor(this.player.getY()),
      this.player.getWidth(),
      this.player.getHeight()
    );

    // draw loot items
    this.lootItems.forEach((item) => {
      this.ctx.drawImage(item.getImage(), item.getX(), item.getY(), item.getWidth(), item.getHeight());
    });
  }

  //auto bind this method to this lass
  updateCharacter = () => {
    this.draw();
  };

  movePlayer() {
    const movePlayerEvent: CustomEvent = new CustomEvent(this.eventName, {
      detail: {
        playerCoordinates: this.player.getCoordinates(),
      },
      bubbles: true,
      composed: true,
    });
    this.scope.dispatchEvent(movePlayerEvent);
  }

  handleKeyPress(event: KeyboardEvent, moving: boolean) {
    switch (event.key) {
      case "ArrowUp":
        this.player.move("UP");
        break;
      case "ArrowDown":
        this.player.move("DOWN");
        break;

      case "ArrowLeft":
        this.player.move("LEFT");
        break;
      case "ArrowRight":
        this.player.move("RIGHT");
        break;

      default:
        break;
    }

    this.updateCharacter();
    if (moving === false) {
      this.movePlayer();
    }
  }

  render() {
    return html`
      <section
        tabindex="0"
        @keydown=${(e: KeyboardEvent) => this.handleKeyPress(e, true)}
        @keyup=${(e: KeyboardEvent) => this.handleKeyPress(e, false)}
      >
        <canvas></canvas>
      </section>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "canvas-game": CanvasGame;
  }
}

// frontend/react/src/features/game/component/CanvasGame.tsx
import React, { useEffect, useRef, useCallback } from "react";
import grass from "../../../assets/images/grass.png";
import playerImage from "../../../assets/images/player.png";
import { Player } from "../model/player";
import type { Item } from "../model/Item";

type CanvasGameProps = {
  lootItems: Item[];
  eventName: string;
  playerX: number;
  playerY: number;
};

export const CanvasGame: React.FC<CanvasGameProps> = ({
  lootItems,
  eventName,
  playerX,
  playerY,
}) => {
  const canvasWidth = 1000;
  const canvasHeight = 600;

  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const ctxRef = useRef<CanvasRenderingContext2D | null>(null);
  const sectionRef = useRef<HTMLElement | null>(null);

  const playerRef = useRef<Player>(
    new Player(0, 0, 64, 64, playerImage, canvasWidth, canvasHeight)
  );

  
  const draw = useCallback(() => {
    const ctx = ctxRef.current;
    const player = playerRef.current;
    if (!ctx) return;

    ctx.clearRect(0, 0, canvasWidth, canvasHeight);

    ctx.drawImage(
      player.getImage(),
      Math.floor(player.getX()),
      Math.floor(player.getY()),
      player.getWidth(),
      player.getHeight()
    );

    lootItems.forEach((item) => {
      ctx.drawImage(
        item.getImage(),
        item.getX(),
        item.getY(),
        item.getWidth(),
        item.getHeight()
      );
    });
  }, [lootItems]);

  
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    canvas.width = canvasWidth;
    canvas.height = canvasHeight;

    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    ctxRef.current = ctx;

    const img = playerRef.current.getImage();
    img.onload = () => draw();

    sectionRef.current?.focus();
  }, [draw]);

  useEffect(() => {
    playerRef.current.updateCoordinates(playerX, playerY);
    draw();
  }, [playerX, playerY, draw]);

 
  const movePlayer = () => {
    const event = new CustomEvent(eventName, {
      detail: {
        playerCoordinates: playerRef.current.getCoordinates(),
      },
      bubbles: true,
      composed: true,
    });

    document.dispatchEvent(event);
  };

  /* ------------------------------
     Keyboard handling
  ------------------------------ */
  const handleKeyPress = (
    event: React.KeyboardEvent,
    moving: boolean
  ) => {
    const player = playerRef.current;

    switch (event.key) {
      case "ArrowUp":
        player.move("UP");
        break;
      case "ArrowDown":
        player.move("DOWN");
        break;
      case "ArrowLeft":
        player.move("LEFT");
        break;
      case "ArrowRight":
        player.move("RIGHT");
        break;
      default:
        return;
    }

    draw();

    if (!moving) {
      movePlayer();
    }
  };

  return (
    <section
      ref={sectionRef}
      tabIndex={0}
      onKeyDown={(e) => handleKeyPress(e, true)}
      onKeyUp={(e) => handleKeyPress(e, false)}
      style={{ outline: "none" }}
    >
      <canvas
        ref={canvasRef}
        style={{
          background: `url(${grass}) no-repeat`,
          backgroundSize: "cover",
          border: "2px solid black",
          imageRendering: "pixelated",
        }}
      />
    </section>
  );
};
